name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # ставим Capacitor + Crosswalk
      - run: npm install
      - run: npx cap sync android
      - run: ./gradlew -p android assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: mindar-demo-apk
          path: android/app/build/outputs/apk/release/*.apk
