name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Код
      - uses: actions/checkout@v4

      # 2. Node
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. Зависимости
      - run: npm install

      # 4-5. Ваши шаги cap init / cap add / gradlew …
      # (оставьте как было, главное — внутри `steps`)

      # 6. Выгрузка APK
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: mindar-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
