name: Build APK

on:
  push:
    branches: [ main ]    # запускается при каждом push в main
  workflow_dispatch:      # можно стартовать вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. код
      - uses: actions/checkout@v4

      # 2. Node
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3. зависимости (подтянет crosswalk-плагин)
      - run: npm install

      # 4. Capacitor: init (если первый раз) и android-платформа
      - name: Capacitor init & add android
        run: |
          npx cap init "MindAR Demo" com.example.mindar --web-dir=www || true
          npx cap add android || true
          npx cap sync android

      # 5. Android SDK
      - uses: android-actions/setup-android@v2
        with:
          api-level: 34

      # 6. сборка debug-apk
      - run: cd android && ./gradlew assembleDebug

      # 7. артефакт
      - uses: actions/upload-artifact@v4
        with:
          name: mindar-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
