name: Build Crosswalk APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 18

    # ⬇️ 1. ставим всё из package.json (crosswalk, permissions, cli, android)
    - run: npm ci || npm install

    # ⬇️ 2. создаём / обновляем платформу Android
    - run: npx cap init "MindAR Demo" com.example.mindar --web-dir=www --npm-client=npm || true
    - run: npx cap add android || true
    - run: npx cap sync android            # копирует плагины

    # ⬇️ 3. устанавливаем Android-SDK 34
    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        accept-android-sdk-licenses: true
        packages: |
          platform-tools
          platforms;android-33
          build-tools;33.0.2

    # ⬇️ 4. собираем debug-apk
    - run: cd android && ./gradlew assembleDebug

    # ⬇️ 5. выкладываем artefact
    - uses: actions/upload-artifact@v4
      with:
        name: mindar-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
